### ISSUE TITLE
Roadmap

### ISSUE THREAD

**Issue by kassane** [kassane/d-zigbuild#2]
### TASKS

- [ ] Add phobos support (complementary & optional)
- [ ] Run druntime tests
- [ ] Some improvements (if needed) - bugfix
- [ ] #1 
- [ ] #3
